name: Java CI

on: [push]

jobs:
#  build:
#    name: Build
#    runs-on: ubuntu-latest
#    steps:
#    - name: trigger single Job
#      uses: appleboy/jenkins-action@master
#      with:
#        url: "http://tom-jerry.club:8011"
#        user: "young"
#        token: "1144d84d50999f7619ec28391519dd22a0"
#        job: "action_test"
   build:
     timeout-minutes: 3
     runs-on: ubuntu-latest

     steps:
     - uses: actions/checkout@v1
     - name: Set up JDK 1.8
       uses: actions/setup-java@v1
       with:
         java-version: 1.8
#     - name: Set up Python 2.7
#       uses: actions/setup-python@v1
#       with:
#         python-version: 2.7
#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install thrift
#     - name: Build with Maven
#       run: |
#         mvn package --file pom.xml
#         cd /home/runner/work/actions/actions/target
#         nohup java -jar thriftTest-1.0-SNAPSHOT.jar &
#     - name: Test
#       run: |
#         cd thrift_test
#         python thrift_client.py
#     - name: Stop
#       run: |
#         kill -9 $(lsof -i tcp:8899 -t)
#   test:
#     timeout-minutes: 3
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v1
#       - name: Test
#         run: |
#           ls
#           cd /home/runner/work/actions/actions/target 
