name: Java CI

on: [push]

jobs:
  build:
    timeout-minutes: 3
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set up Python 2.7
      uses: actions/setup-python@v1
      with:
        python-version: 2.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install thrift
    - name: Build with Maven
      run: |
      mvn package --file pom.xml
      cd /home/runner/work/actions/actions/target
      nohup java -jar actions-0.0.1-SNAPSHOT.jar &
    - name: stop
      run: |
        kill -9 $(lsof -i tcp:8899 -t)
